events{}

http {
  # Apuntar al contenedor de la página 
  upstream frontend {
    server frontend:3000;
  }

  #Apuntar al contenedor de la API 
  upstream middleware {
    server middleware:8080; 
  }

  server {
    listen 8000;

    # Avisar al servicio quién hizo la petición 
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Fowarded-Proto $scheme;

    # Mandar la API al middleware con la ruta completa 
    location /api/ {
      # Sin / al final para que se mande la ruta completa (/api/tablas/resolver)
      proxy_pass http://middleware;

      # Poner a nginx al inicio del recorrido del front 
      proxy_hide_header X-Nodo;
      add_header X-Nodo "nginx-gateway, $upstream_http_x_nodo" always;
    }

    # Mandar todo lo demás a la página 
    location / {
      proxy_pass http://frontend;
    }

    # Repsponder que nginx está vivo 
    location = /salud {
      return 200 "nginx-gateway vivo";
    }
  }
}
